config/routes.rb
Rails.application.routes.draw do

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  root to: 'home#index'
  get 'import', to: 'import#index'
  get 'import/add', to: 'import#add'

  resources :settings, except: [:edit, :new], param: :var

  resources :artists, only: [:index, :show, :update]

  resources :genres, only: [:index, :show]

  resources :albums, only: [:index, :show, :update]

  resources :tracks, except: [:edit, :new] do
    member do
      get :data
    end
  end

  resources :flexlists, except: [:edit, :new]

  resources :playlists, except: [:edit, :new]
end

app/models/album.rb
class Album < ActiveRecord::Base
  #include Elasticsearch::Model
  #include Elasticsearch::Model::Callbacks
  extend FriendlyId

  # An album is composed of 1 or more tracks
  has_many :tracks

  # An album is part of an artist's collection
  belongs_to :artist

  # An album can be of many genres
  has_and_belongs_to_many :genres

  has_attached_file :cover, styles: { large: '600x600>',
                                      medium: '300x300>',
                                      small: '175x175>',
                                      thumb: '100x100>'}


  friendly_id :slug_candidates, use: [:slugged, :finders]

  # Name is another way of getting title
  alias_attribute :name, :title

  # Album cover -> art
  alias_attribute :art, :cover

  # Ensure we have a title and artist
  validates :title, :artist, presence: true

  # Ensure each album title is unique to an artist
  validates :title, uniqueness: { case_sensitive: false, scope: :artist }

  # Ensure our artist is valid
  validates_associated :artist

  # Ensure is_compilation is either true or false
  validates :is_compilation, inclusion: { in: [true, false] }

  # Ensure rating is an integer from 0 to 5
  validates :rating, numericality: {
                      only_integer: true,
                      greater_than_or_equal_to: 0,
                      less_than_or_equal_to: 5
                    }

  # Ensure num_discs is an integer greater than 0
  validates :num_discs, numericality: {
                          only_integer: true,
                          greater_than: 0,
                          allow_nil: true
                        }

  # Make sure our cover is an image
  validates_attachment_content_type :cover, :content_type => /\Aimage\/.*\Z/

  scope :artist, -> artist { includes(:artist).where('artists.slug = ? ', artist).references(:artist) }
  scope :genre, -> genre { includes(:genres).where('genres.slug = ? ', genre).references(:genres) }
  scope :rating, -> rating { where(rating: rating) }
  scope :is_compilation, -> { where(is_compilation: true) }
  scope :year, -> year { where('release_date >= ? and release_date <= ?', "#{year}-01-01", "#{year}-12-31")}

  def slug_candidates
    [
      :title,
      [:title, :artist],
      [:title, :artist, :release_year]
    ]
  end

  def num_tracks
    tracks.count
  end

  def average_rating
    tracks.average(:rating)
  end

  def release_year
    release_date.try(:year)
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]
  has_scope :artist
  has_scope :genre
  has_scope :rating
  has_scope :is_compilation, type: :boolean
  has_scope :year

  # GET /albums
  # GET /albums.json
  def index
    @albums = apply_scopes(Album).all
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
  end

  # GET /albums/1/edit
  def edit
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    @album = Album.find(params[:id])
    @album.artist = Artist.find_or_initialize_by(name: params[:artist]) do
      rating = 0
    end
    unless params[:genres].nil?
      @album.genres = []
      params[:genres].each { |genre| @album.genres << Genre.find_or_initialize_by(name: genre) }
    end
    @album.slug = nil
    respond_to do |format|
      if @album.update(album_params)
        format.json { render json: {
            album: @album.slug,
            artist: @album.artist.slug,
            notice: 'Album was successfully updated.'
        }, status: :ok, location: @album }
      else
        format.json { render json: { errors: @album.errors.full_messages }, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:title, :rating, :artist, :release_date, :is_compilation)
    end
end

app/views/albums/_form.html.haml
= form_for(@album, html:{ multipart:true, class: 'pure-form pure-form-aligned' }) do |f|
  %fieldset
    - if @album.errors.any?
      #error_explanation
        %h2
          = pluralize(@album.errors.count, "error")
          prohibited this album from being saved:
        %ul
          - @album.errors.full_messages.each do |message|
            %li= message
    .pure-control-group
      = f.label :title
      = f.text_field(:title, required: true, placeholder: 'Album Title' )
    .pure-control-group
      = f.label 'Album Artist'
      = f.collection_select('artist', Artist.order(:name), :name, :name, prompt: 'Select artist')
    .pure-control-group
      = f.label :rating
      = f.number_field :rating, in:0..5, placeholder: "0 to 5"
    .pure-control-group
      = f.label 'Cover Art'
      = f.file_field :cover
    .pure-control-group
      = f.label :release_date
      = f.date_select :release_date, order: [:year], start_year: 1900, end_year: Time.now.year, prompt: {year: 'Select year'}
    .pure-control-group
      = f.label 'Compilation?'
      = f.check_box :is_compilation
    .pure-controls
      = f.submit 'Save Album', class: 'pure-button pure-button-primary'
:javascript
    $('select').filter(function() {
      return this.id.match(/.+_date_1i/)
    }).selectize();

    $('select').filter(function () {
      return this.id.match(/.+_artist/)
    }).selectize({
      create: true,
      sortField: 'text'
    });

app/views/albums/edit.html.haml
.header
  %h1 Editing album
.content
  = render 'form'
  = link_to 'Show', @album
  |
  \#{link_to 'Back', albums_path}