config/routes.rb
Rails.application.routes.draw do

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  root to: 'home#index'
  get 'import', to: 'import#index'
  get 'import/add', to: 'import#add'

  resources :settings, except: [:edit, :new], param: :var

  resources :artists, only: [:index, :show, :update]

  resources :genres, only: [:index, :show]

  resources :albums, only: [:index, :show, :update]

  resources :tracks, except: [:edit, :new] do
    member do
      get :data
    end
  end

  resources :flexlists, except: [:edit, :new]

  resources :playlists, except: [:edit, :new]
end

app/models/flexlist.rb
class Flexlist < ActiveRecord::Base
  include Playable
  extend FriendlyId

  has_many :rules

  friendly_id :name,  use: [:slugged, :finders]

  enum match: [:any_rules, :all_rules]

  validates :match, presence: true
end

app/controllers/flexlists_controller.rb
class FlexlistsController < ApplicationController
  before_action :set_flexlist, only: [:show, :edit, :update, :destroy]

  # GET /flexlists
  def index
    @flexlists = Flexlist.all
  end

  # GET /flexlists/1
  def show
  end

  # POST /flexlists
  def create
    @flexlist = Flexlist.new(flexlist_params)

    if @flexlist.save
      render json: { flexlist: @flexlist, notice: 'Flexlist was successfully created.' }, status: :created, location: @flexlist
    else
      render json: { errors: @flexlist.errors.full_messages }, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /flexlists/1
  def update
    if @flexlist.update(flexlist_params)
      render json: {flexlist: @flexlist.slug, notice: 'Flexlist was successfully updated.'}, status: :ok, location: @flexlist
    else
      render json: { errors: @flexlist.errors.full_messages }, status: :unprocessable_entity
    end
  end

  # DELETE /flexlists/1
  def destroy
    @flexlist.destroy
    head :no_content
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flexlist
      @flexlist = Flexlist.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def flexlist_params
      params.require(:flexlist).permit(:name, :match)
    end
end

app/views/flexlists/_form.html.slim
= form_for @flexlist do |f|
  - if @flexlist.errors.any?
    #error_explanation
      h2 = "#{pluralize(@flexlist.errors.count, "error")} prohibited this flexlist from being saved:"
      ul
        - @flexlist.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .actions = f.submit 'Save'

app/views/flexlists/edit.html.slim
h1 Editing flexlist

== render 'form'

= link_to 'Show', @flexlist
'|
= link_to 'Back', flexlists_path

app/views/flexlists/new.html.slim
h1 New flexlist

== render 'form'

= link_to 'Back', flexlists_path